"""initial_schema

Revision ID: 8c4d3e9027bf
Revises: 
Create Date: 2026-05-13 20:36:05.126963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8c4d3e9027bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_server_id'), 'alert_events', ['server_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.Enum('GREATER_THAN', 'LESS_THAN', 'EQUALS', name='alert_condition'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_server_id'), 'alert_rules', ['server_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('metrics',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('CPU_USAGE', 'RAM_USAGE', 'SWAP_USAGE', 'DISK_USAGE', 'DISK_IO_READ', 'DISK_IO_WRITE', 'LOAD_AVG_1', 'LOAD_AVG_5', 'LOAD_AVG_15', 'NETWORK_IN', 'NETWORK_OUT', 'PROCESS_COUNT', 'CPU_TEMP', name='metric_type'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_server_id'), 'metrics', ['server_id'], unique=False)
    op.create_index('ix_metrics_server_type_ts', 'metrics', ['server_id', 'metric_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    op.create_table('notification_channels',
    sa.Column('channel_type', sa.Enum('EMAIL', 'TELEGRAM', 'WEBHOOK', name='channel_type'), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table('odoo_metrics',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('workers_active', sa.Integer(), nullable=False),
    sa.Column('processes_hung', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Float(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('requests_concurrent', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odoo_metrics_server_id'), 'odoo_metrics', ['server_id'], unique=False)
    op.create_index('ix_odoo_metrics_server_ts', 'odoo_metrics', ['server_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_odoo_metrics_timestamp'), 'odoo_metrics', ['timestamp'], unique=False)
    op.create_table('pg_metrics',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('connections_active', sa.Integer(), nullable=False),
    sa.Column('slow_queries', sa.Integer(), nullable=False),
    sa.Column('locks', sa.Integer(), nullable=False),
    sa.Column('deadlocks', sa.Integer(), nullable=False),
    sa.Column('db_size_mb', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pg_metrics_server_id'), 'pg_metrics', ['server_id'], unique=False)
    op.create_index('ix_pg_metrics_server_ts', 'pg_metrics', ['server_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_pg_metrics_timestamp'), 'pg_metrics', ['timestamp'], unique=False)
    op.create_table('servers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=100), nullable=False),
    sa.Column('ssh_password_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('ssh_key_encrypted', sa.String(length=5000), nullable=True),
    sa.Column('server_type', sa.Enum('PRODUCTION', 'STAGING', 'DEVELOPMENT', name='server_type'), nullable=False),
    sa.Column('environment', sa.Enum('PRODUCTION', 'STAGING', 'DEVELOPMENT', name='environment'), nullable=False),
    sa.Column('monitoring_interval', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'READONLY', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('servers')
    op.drop_index(op.f('ix_pg_metrics_timestamp'), table_name='pg_metrics')
    op.drop_index('ix_pg_metrics_server_ts', table_name='pg_metrics')
    op.drop_index(op.f('ix_pg_metrics_server_id'), table_name='pg_metrics')
    op.drop_table('pg_metrics')
    op.drop_index(op.f('ix_odoo_metrics_timestamp'), table_name='odoo_metrics')
    op.drop_index('ix_odoo_metrics_server_ts', table_name='odoo_metrics')
    op.drop_index(op.f('ix_odoo_metrics_server_id'), table_name='odoo_metrics')
    op.drop_table('odoo_metrics')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index('ix_metrics_server_type_ts', table_name='metrics')
    op.drop_index(op.f('ix_metrics_server_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_rules_server_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_events_server_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
